# Assignment

Q1. Write the NumPy program to create a 2d array with 6 on the border
and 0 inside?

    Expected OutputOriginal array-
    [ [6 6 6 6 6]
     [ 6 6 6 6 6]
     [ 6 6 6 6 6 ]
    [ 6 6 6 6 6 ]
    [ 6 6 6 6 ] ].
    6 on the border and 0 inside in the array-
    [[ 6 6 6 6 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 6 6 6 6]].

In [15]:
def psaVedNumpyMatrixWithBorderSix():
    import numpy as np
    shapeMatrix = np.full(shape=[6,6],fill_value=6,dtype=np.int)
    sixReshapeMatrix = shapeMatrix.reshape(6,6)
    sixReshapeMatrix[1:-1,1:-1] = 0
    return sixReshapeMatrix
psaVedNumpyMatrixWithBorderSix()

array([[6, 6, 6, 6, 6, 6],
       [6, 0, 0, 0, 0, 6],
       [6, 0, 0, 0, 0, 6],
       [6, 0, 0, 0, 0, 6],
       [6, 0, 0, 0, 0, 6],
       [6, 6, 6, 6, 6, 6]])

Q2. Write the NumPy program to create a 8x8 matrix and fill it with the
checkerboard pattern?
    
    Checkerboard pattern-
    [[3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]].

In [14]:
def psaVedCheckerboardPattern():
    import numpy as np
    resultData = np.full(shape=[8,8],fill_value=3,dtype=np.int)
    resultData[1::2,::2] = 9
    resultData[0::2,1::2] = 9
    return resultData
psaVedCheckerboardPattern()

array([[3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3],
       [3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3],
       [3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3],
       [3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3]])

Q3. Write the NumPy program to create an empty and a full array.
 
     Expected Output-
    [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
    [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
    [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]
    [[6 6 6]
    [6 6 6]
    [6 6 6]]


In [16]:
def psaVedEmptyAndFullArray():
    import numpy as np
    empty = np.empty((3,3))
    full = np.full((3,3),9,int)
    print(empty)
    print(full)
psaVedEmptyAndFullArray()

[[1.0869444e-322 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 3.6758484e-321]
 [0.0000000e+000 0.0000000e+000 1.1919556e-317]]
[[9 9 9]
 [9 9 9]
 [9 9 9]]


Q4. Write the NumPy program to convert the values of Centigrade
degrees into the Fahrenheit degrees and the centigrade values are
stored in the NumPy array.
    
    Sample Array -[0, 12, 45.21 ,34, 99.91]
    Expected OutputValues in Fahrenheit degrees-
    [ 0. 12. 45.21 34. 99.91]
    Values in Centigrade degrees-
    [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [17]:
def psaVedCentigradeFahrenheit():
    import numpy as np
    rawData = np.array([0, 12, 45.21 ,34, 99.91])
    print(rawData)
    centiData = (5*rawData/9 - 5*32/9)
    print(centiData)
psaVedCentigradeFahrenheit()

[ 0.   12.   45.21 34.   99.91]
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


Q5. Write the NumPy program to find the real and imaginary parts of an
array of complex numbers?

    Expected OutputOriginal array [ 1.00000000+0.j 0.70710678+0.70710678j]
    Real part of the array-
    [ 1. 0.70710678]
    Imaginary part of the array-
    [ 0. 0.70710678]

In [29]:
def psaVedImaginaryPart():
    import numpy as np
    originalData = np.sqrt([1+0j])
    print(originalData.real)
    print(originalData.imag)
psaVedImaginaryPart()

[1.]
[0.]


Q6. Write the NumPy program to test whether each element of a 1-D
array is also present in the second array?

    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


In [31]:
def psaVedCheckPresence(first6,second6):
    import numpy as np
    oneArray = np.array(first6)
    twoArray = np.array(second6)
    print(np.in1d(oneArray,twoArray))
psaVedCheckPresence([0, 10, 20, 40, 60],[0, 40])

[ True False False  True False]


Q7. Write the NumPy program to find common values between two
arrays?
    
    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [10, 30, 40]
    Common values between two arrays-
    [10 40]

In [34]:
def psaVedCommanValue(first7,second7):
    import numpy as np
    oneArray = np.array(first7)
    twoArray = np.array(second7)
    print(np.intersect1d(oneArray,twoArray))
psaVedCommanValue([0, 40],[0, 10, 20, 40, 60])

[ 0 40]


Q8. Write the NumPy program to get the unique elements of an array?

    Expected OutputOriginal array-
    [10 10 20 20 30 30]
    Unique elements of the above array-
    [10 20 30]
    P a g e 14 | 44
    Original array-
    [[1 1]
    [2 3]]
    Unique elements of the above array-
    [1 2 3]

In [38]:
def psaVedUniqueElement(first8):
    import numpy as np
    oneArray = np.array(first8)
    return np.unique(oneArray)
psaVedUniqueElement([[1, 1],[2, 3]])

array([1, 2, 3])

Q9. Write the NumPy program to find the set exclusive-or of two arrays.
Set exclusive-or will return the sorted, unique values that are in
only one (not both) of the input arrays?

    Array1- [ 0 10 20 40 60 80]
    Array2- [10, 30, 40, 50, 70]
    Unique values that are in only one (not both) of the input arrays-
    [ 0 20 30 50 60 70 80]

In [39]:
def psaVedExor(first9,second9):
    import numpy as np
    oneArray = np.array(first9)
    twoArray = np.array(second9)
    return np.setxor1d(oneArray,twoArray)
psaVedExor([0, 10, 20, 40, 60, 80],[10, 30, 40, 50, 70])

array([ 0, 20, 30, 50, 60, 70, 80])

Q10. Write the NumPy program to test if all elements in an array
evaluate to True ?
 
Note: 0 evaluates to False in NumPy

In [50]:
def psaVedEvaluate(first10):
    import numpy as np
    oneArray = np.all(first10)
    return oneArray
psaVedEvaluate([10, 20,0, -50])

False

Q11. Write the NumPy program to test whether any array element along
the given axis evaluates to True?
 
Note: 0 evaluates to False in NumPy

In [49]:
def psaVedEvaluateAnyFalse(first11):
    import numpy as np
    oneArray = np.any(first11)
    return oneArray
psaVedEvaluateAnyFalse([0, 0,0, 0])

False

Q12. Write the NumPy program to construct an array by repeating?

    Sample array- [1, 2, 3, 4]
    Expected OutputOriginal array
    [1, 2, 3, 4]
    Repeating 2 times
    [1 2 3 4 1 2 3 4]
    Repeating 3 times
    [1 2 3 4 1 2 3 4 1 2 3 4]

In [55]:
def psaVedRepeatArrayValue(first12,second12):
    import numpy as np
    return np.tile(first12,second12)
psaVedRepeatArrayValue([1, 2, 3, 4],3)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

Q13. Write the NumPy program to find the indices of the maximum and
minimum values with the given axis of an array?

    Original array- [1 2 3 4 5 6]
    Maximum Values- 5
    Minimum Values- 0

In [59]:
def psaVedCheckIndexes(first13):
    print('Minimum Index:- '+ '0')
    print('Manimum Index:- ')
    print(len(first13)-1)
psaVedCheckIndexes([1, 2, 3, 4, 5, 6])

Minimum Index:- 0
Manimum Index:- 
5


In [60]:
def psaVedCheckingIndexes(first13):
    import numpy as np
    print('Minimum Index:- ')
    print(np.argmin(first13))
    print('Manimum Index:- ')
    print(print(np.argmax(first13)))
psaVedCheckingIndexes([1, 2, 3, 4, 5, 6])

Minimum Index:- 
0
Manimum Index:- 
5
None


Q14. Write the NumPy program compare two arrays using numpy?

    Array a- [1 2]
    Array b- [4 5]
    a > b
    [False False]
    a >= b
    [False False]
    a < b
    [ True True]
    a <= b
    [ True True]


In [64]:
def psaVedCompareArray(first14,second14):
    import numpy as np
    oneArray = np.array(first14)
    twoArray = np.array(second14)
    print(np.greater(oneArray, twoArray))
    print(np.greater_equal(oneArray, twoArray))
    print(np.less(oneArray, twoArray))
    print(np.less_equal(oneArray, twoArray))
psaVedCompareArray([1, 2],[4, 5])

[False False]
[False False]
[ True  True]
[ True  True]


Q15. Write the NumPy program to sort an along the first, last axis of an
array?

    Sample array- [[2,5],[4,4]]
    Expected OutputOriginal array:
    [[4 6]
    [2 1]]
    Sort along the first axis:
    [[2 1]
    [4 6]]
    Sort along the last axis-
    [[1 2]
    [4 6]]

In [70]:
def psaVedSortArrayElement(first15):
    import numpy as np
    oneArray = np.array(first15)
    print(oneArray)
    print(np.sort(oneArray,axis=0))
    print(np.sort(oneArray,axis=1))
psaVedSortArrayElement([[2,1],[4,6]])

[[2 1]
 [4 6]]
[[2 1]
 [4 6]]
[[1 2]
 [4 6]]


Q16. Write the NumPy program to sort pairs of first name and last name
return their indices (first by last name, then by first name).

    first_names - ( Betsey, Shelley, Lanell, Genesis, Margery )
    last_names - ( Battle, Brien, Plotner, Stahl, Woolum )
    Expected Output-
    [1 3 2 4 0]

In [78]:
def psaVedLexsortArray(first16,second16):
    import numpy as np
    return np.lexsort((first16, second16))
psaVedLexsortArray(('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis'),('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl'))

array([1, 3, 2, 4, 0], dtype=int64)

Q17. Write the NumPy program to get the values and indices of the
elements that are bigger than 10 in the given array?

    Original array-
    [[ 0 10 20]
    [20 30 40]]
    Values bigger than 10 = [20 20 30 40]
    Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [82]:
def psaVedIndexOfBiggerValue(first17):
    import numpy as np
    arrayData = np.array(first17)
    return np.where(arrayData > 10)
psaVedIndexOfBiggerValue([[0, 10, 20],[20, 30, 40]])

(array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))

Q18. Write the NumPy program to find the memory size of a NumPy
array?

    Expected Output128 bytes


In [83]:
def psaVedMemorySizeOfArray(first18):
    import numpy as np
    arrayData = np.array(first18)
    print(arrayData.size*arrayData.itemsize)
psaVedMemorySizeOfArray([[0, 10, 20],[20, 30, 40]])

24


## Great Job!